# Generated by Django 4.2.3 on 2023-08-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default=None, upload_to="images/posts", verbose_name="Изображение"
            ),
        ),
    ]
