# Generated by Django 4.2.3 on 2023-08-07 14:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("twitter", "0002_alter_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(max_length=200, verbose_name="Комментарии"),
                ),
                (
                    "comment_data",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 8, 7, 14, 12, 18, 272700, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Дата комментирования",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="twitter.post",
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коментарий",
                "verbose_name_plural": "Коментария",
                "ordering": ("-comment_data", "post_id"),
            },
        ),
    ]
