# Generated by Django 4.2.3 on 2023-08-18 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0006_alter_comment_author_alter_comment_comment_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="commentratings",
            old_name="comment_id",
            new_name="comment",
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_data",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 18, 13, 30, 24, 330486, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата комментирования",
            ),
        ),
    ]
