# Generated by Django 4.2.3 on 2023-10-11 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0007_rename_post_id_comment_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_data",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 11, 14, 12, 3, 920114, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата комментирования",
            ),
        ),
    ]
