# Generated by Django 4.2.3 on 2023-10-14 00:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("twitter", "0011_alter_comment_comment_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_data",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 14, 0, 33, 11, 510431, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата комментирования",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/avatars",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "gif", "jpeg"]
                            )
                        ],
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "was_born",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Фамилия"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
                "ordering": ("-was_born", "user"),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Тема сообщений",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщений")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            14,
                            0,
                            33,
                            11,
                            509450,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-timestamp", "subject"],
            },
        ),
    ]
