# Generated by Django 4.2.3 on 2023-10-20 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0013_alter_comment_comment_data_alter_message_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_data",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 20, 3, 58, 15, 448950, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата комментирования",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 20, 3, 58, 15, 448950, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
