# Generated by Django 4.2.3 on 2023-10-20 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0015_message_answered_alter_comment_comment_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_data",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 20, 4, 55, 48, 293589, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата комментирования",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 20, 4, 55, 48, 293589, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
