# Generated by Django 4.2.3 on 2023-10-21 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0017_message_is_edited_alter_comment_comment_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_data",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 21, 16, 6, 37, 229102, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата комментирования",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 21, 16, 6, 37, 228102, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
