# Generated by Django 4.2.3 on 2023-10-22 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0018_message_is_opened_message_is_viewed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_data",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата комментирования"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
