# Generated by Django 4.2.3 on 2023-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0019_alter_comment_comment_data_alter_message_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="was_born",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
