# Generated by Django 4.2.3 on 2023-10-23 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitter", "0020_alter_userprofile_was_born"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="6596121.png",
                null=True,
                upload_to="images/avatars",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "gif", "jpeg"]
                    )
                ],
                verbose_name="Аватар",
            ),
        ),
    ]
